apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: utils-tools
    qcloud-app: utils-tools
  name: utils-tools
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: utils-tools
      qcloud-app: utils-tools
  template:
    metadata:
      labels:
        k8s-app: utils-tools
        qcloud-app: utils-tools
    spec:
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: container
          value: docker
        image: v-pmwjiang-tcr.tencentcloudcr.com/my/utils:v1
        imagePullPolicy: IfNotPresent
        name: utils-tools
        imagePullSecrets:
        - name: tcr
        name: utils-tools

