apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: redis
    qcloud-app: redis
  name: redis
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: redis
      qcloud-app: redis
  template:
    metadata:
      labels:
        k8s-app: redis
        qcloud-app: redis
    spec:
        image: v-pmwjiang-tcr.tencentcloudcr.com/my/redis:latest
        imagePullPolicy: IfNotPresent
        imagePullSecrets:
        - name: qcloudregistrykey
        name: redis

